### ISSUE TITLE
Can we resize this grid using mouse?

### ISSUE THREAD

**Issue by Tonku** [shyndman/flutter_layout_grid#68]
Can we do something like this widget

https://pub.dev/packages/resizable_widget

**Comment by shyndman** [comment]
Not directly, but you can build something like this using the package. In fact, I did exactly this for an application I wrote.

Are you looking for something out of the box, or would you like some advice on how to write it?

**Comment by Tonku** [comment]
Thanks for the info @shyndman 
I am building a drag and drop app, for that I need a resizable grid, if you have something out of the box , would you be interested in making it available via pub.dev ?

**Comment by shyndman** [comment]
Hey @Tonku, sorry for the long wait on this.

I may have worded that poorly. I do **not** have something out of the box. The software I wrote wasn't general purpose, and was designed specifically for the application I was writing.

**Comment by shyndman** [comment]
I'd be happy to offer advice if you wanted to write something on your own.
