### ISSUE TITLE
Exceptions are thrown with ListView children

### ISSUE THREAD

**Issue by shyndman** [shyndman/flutter_layout_grid#71]
This is something that should work.

**Comment by oravecz** [comment]
I believe I am running into this problem with ExpansionPanelList/ExpansionPanel also. Renders ok, but when I expand it crashes. This will be a blocker for me unless a workaround exists. Any thoughts?

**Comment by shyndman** [comment]
Can you post a reproduction?

**Comment by shyndman** [comment]
Oh, I see. This isn't a new bug.

Let me take a look.

**Comment by shyndman** [comment]
I'm actually not able to reproduce this in a simple case. Mind providing some code so I can take a look? I'm reasonably sure we can get this running.

**Comment by oravecz** [comment]
My example is too complicated (and closed source), but I can duplicate something like it with these steps.

### Start with your "basic" example

### Add code that I lifted from Flutter API docs (ExpansionPanelList API) to the bottom of the example

```dart
List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    return Item(
      headerValue: 'Panel $index',
      expandedValue: 'This is item number $index',
    );
  });
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<Item> _data = generateItems(8);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        height: 300,
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },
      children: _data.map<ExpansionPanel>((Item item) {
        return ExpansionPanel(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
              subtitle:
                  const Text('To delete this panel, tap the trash can icon'),
              trailing: const Icon(Icons.delete),
              onTap: () {
                setState(() {
                  _data.removeWhere((Item currentItem) => item == currentItem);
                });
              }),
          isExpanded: item.isExpanded,
        );
      }).toList(),
    );
  }
}
```

### Modify the first `GridPlacement`

```dart
          GridPlacement(
            rowStart: 0,
            columnStart: 0,
            columnSpan: 4,
            child: Container(
              color: Colors.blue,
              padding: const EdgeInsets.all(8),
              child: const MyStatefulWidget(),
            ),
          ),
```

I receive cascading render assertion failures.

### Flutter Doctor

[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.5.1 21G83 darwin-arm (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by shyndman** [comment]
The problem appears to be this line:

https://gist.github.com/shyndman/208f25b1362901ca74b11ad4185c1fd1#file-basic_with_expansion-dart-L137

The list is saying "I need to be able to grow infinitely on the y-axis", and that container is saying "nope".

Removing the height constraint allows the container (and the expansion panel list) to inherit the viewport's constraints, which are infinite on y.

Does that help?

**Comment by oravecz** [comment]
Sorry, I added the height when I was trying to debug. Your right it doesn't crash when removing height, but it doesn't render properly either. It is clipped within the bounds of the GridPlacement.

![image](https://user-images.githubusercontent.com/297712/193023237-3dcf01ef-117b-42f2-832a-0a75ca602e99.png)

Also, I'll see if I can reduce my example (of it throwing an error when I expand my ExpansionPanel) as a reproducible test case.

**Comment by shyndman** [comment]
Thank you. That'd be great.

Right, so that clipping is intentional. If you supply a fixed size (32px here) it will render at exactly that height, and never measure the children. This performs considerably better when you can away with it.

When you want the children's sizes to be considered, use `auto`.

**Comment by oravecz** [comment]
When I set the row to `auto`, it indeed initially renders as expected. But, I would also expect `auto` row to change its bounds as the children within shrink/grow. With the example I provided, the row initially lays out to encompass the ExpansionPanelList (with some additional space at the bottom of the row I haven't yet debugged). 

(My fonts are messed up somehow in the screenshot)
![image](https://user-images.githubusercontent.com/297712/193033704-03deb593-050d-4384-8915-b410a6ba6539.png)

However, as I expand or remove items from the list, nothing happens to the layout and the component overflows or contracts with no additional layout. Expected or bug?

**Comment by shyndman** [comment]
Offhand, I'm not sure. It _seems_ like something it should be able to handle, but I will have to look at the messages being passed up and down the tree.

I'll have a chance to take a look at this tomorrow.

**Comment by shyndman** [comment]
I actually seem to recall that I'm asking children to be notified of size changes, so it could be that I'm missing a piece necessary to handle some cases? We'll see.

**Comment by oravecz** [comment]
If you are using CustomMultiChildLayout behind the scenes, the delegate has a relayout listener that you can attach in its constructor. Not sure exactly _what_ you attach or how you listen for any widgets in the tree which can change their size, or more specifically, whether your children change their size.

**Comment by shyndman** [comment]
I've verified that I'm listening for size changes, and that I'm receiving them.

https://github.com/shyndman/flutter_layout_grid/blob/fd45e3255cf215d5b7839d72934a14ed18fa2258/lib/src/rendering/track_size.dart#L110-L128

These `RenderBox.get*Intrinsic{Width,Height}` methods are called during the sizing of `auto` tracks. Calling them indicates to the children that the parent uses their sizing to layout, and any change to their size will result in a `grid.markNeedsLayout()`

https://api.flutter.dev/flutter/rendering/RenderBox/getMaxIntrinsicWidth.html

**Comment by shyndman** [comment]
I suspect that what you're running into is like the left-hand side here:

![image](https://user-images.githubusercontent.com/42326/193639066-086b8020-0f4b-4ea3-be77-acb506fad295.png)

**Comment by BadPistol97** [comment]
I need help with this. 

![image](https://user-images.githubusercontent.com/42179618/201041450-89b18af8-418e-4b41-81f0-85a2485c7a09.png)

`
@override
  Widget build(BuildContext context, WidgetRef ref){

    final List<TrackSize> rowSize = repeat(content.length,[auto]);

    return  LayoutGrid(
      columnSizes: repeat(count,[auto]),
      rowSizes: rowSize.isEmpty ? [auto] : rowSize,
      columnGap: 0,
      rowGap: 0,
      children: content,
    );

}`

**Comment by shyndman** [comment]
Hi there,

Would you mind uploading a higher quality screenshot? And ideally a bit more code?

**Comment by BadPistol97** [comment]
What I wanted to achieve is having multiple expansion tile in the grid layout. 

![image](https://user-images.githubusercontent.com/42179618/201464969-2f5ebc7e-8b0c-4b9a-8825-d1bf5e2d5758.png)

there were overflows because I had a list view in the children of the expansion tile without specifying its height (I guess that's the issue). 

I swapped it out with a container now it is scaling with the content of the expansion tile without breaking the grid layout. 

Thanks.

**Comment by shyndman** [comment]
👍
