### ISSUE TITLE
dynamic list itemcount and pagination

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [shyndman/flutter_layout_grid#75]
Can I use this package for the dynamic grid list? I mean I don't know exactly the list length, which is coming from api.

my `crossAxisCount` is 2.  but I don't know item count will be 2, 3, 7, or 9. 

I'm asking especially for `columnSizes` and `rowSizes` properties.

and can I do pagination? 

I'm coming from here: https://codewithandrea.com/articles/flutter-layout-grid-content-sized-items/.

**Comment by shyndman** [comment]
Hi @Shahmirzali-Huseynov,

> my crossAxisCount is 2. but I don't know item count will be 2, 3, 7, or 9.

How about something like this?

```dart
final List items; // This is the list of items from your server
return LayoutGrid(
  columnSizes: [1.fr, 1.fr], // ...or whatever
  // repeat is a helper function useful in this case
  // repeat(4, [auto]) == [auto, auto, auto, auto] 
  rowSizes: repeat(items.length, [auto]), 
  children: items.expand((item) {
    return [ 
      Text(item.name),
      Text(item.value),
    ];
  }).toList(),
);
```

> and can I do pagination?

Sure! It shouldn't be too hard to implement in your app. Let me know if you need an example.

**Comment by Shahmirzali-Huseynov** [comment]
> Hi @Shahmirzali-Huseynov,
> 
> > my crossAxisCount is 2. but I don't know item count will be 2, 3, 7, or 9.
> 
> How about something like this?
> 
> ```dart
> final List items; // This is the list of items from your server
> return LayoutGrid(
>   columnSizes: [1.fr, 1.fr], // ...or whatever
>   // repeat is a helper function useful in this case
>   // repeat(4, [auto]) == [auto, auto, auto, auto] 
>   rowSizes: repeat(items.length, [auto]), 
>   children: items.expand((item) {
>     return [ 
>       Text(item.name),
>       Text(item.value),
>     ];
>   }).toList(),
> );
> ```
> 
> > and can I do pagination?
> 
> Sure! It shouldn't be too hard to implement in your app. Let me know if you need an example.

@shyndman thank you for answering. Yes, sure. I want an example 😊👍

**Comment by Shahmirzali-Huseynov** [comment]
@shyndman  ? can you give example ?
