### ISSUE TITLE
Layout with uneven columns and centring for a row

### ISSUE THREAD

**Issue by ominibyte** [shyndman/flutter_layout_grid#82]
Hi, thanks for your work on this so far.

I am wondering if it is possible to achieve something like this using any of the placement strategies.

![image](https://user-images.githubusercontent.com/7020327/164957071-f1255328-816b-4673-ac67-bb73f1d2d072.png)

So far, I cannot seem to find documentation for that. I am interested in the top row being centred. 

Thanks.

**Comment by shyndman** [comment]
Hey, sorry for the wait.

You could do this in a couple of ways. Are you still interested?

**Comment by ominibyte** [comment]
Yes I am still interested. Thanks for getting back to me.

Any help would be appreciated 🙏🏾.

**Comment by shyndman** [comment]
OK, I'll give it a shot and see what I can come up with.

**Comment by shyndman** [comment]
Nope, I couldn't get this going. It's impossible to keep the items together unless they have a flexible size (and I assume you want to keep aspect ratios intact?)

This is more easily accomplished with Rows and Columns. Something like this:

https://dartpad.dartlang.org/?id=808da6f52a1c3d8d550057d07dc12ec4

**Comment by ominibyte** [comment]
Oh wow. Thanks for trying.

Yes I want to keep the aspect ratio. The number of cells is also dynamic. I
just found it difficult getting it to work for uneven cell numbers.

Thanks again for your help.

**Comment by shyndman** [comment]
I was walking the dog and had one more idea. Let me give it a shot.

**Comment by shyndman** [comment]
Aha! I got something going.

I realized that if I constrained the entire grid with an AspectRatio, I could keep the videos independently constrained, and nothing would be drifting apart.

https://user-images.githubusercontent.com/42326/167226499-c476e0fe-085f-4889-99b9-9ee24cf84585.mov

Here's the code: https://gist.github.com/shyndman/5660d4e68e6d80f01fa48830bceb44bb

I'm closing this off, but post back if you need anything.

**Comment by ominibyte** [comment]
Thank you so much. 🙏🏾

I will adopt your solution.
