### ISSUE TITLE
How can I handle interaction with row?

### ISSUE THREAD

**Issue by 0Franky** [shyndman/flutter_layout_grid#86]
Hi shyndman,
thank you for your work and this plugin.

I want to ask you how I can handle the interaction with a row.
For example if you wanted to highlight the entire row when the mouse is over it or a click.

Thank you in advanced.

**Comment by shyndman** [comment]
hey @0Franky,

Sorry, I totally missed this. Hope you still need it.

So the grid doesn't do that sort of thing for you, but it's really easy to add yourself.

The basic idea is that you're going to have to create your own Row widget class, and handle the kinds of interaction you're interested in.

Would an example be helpful?
