### ISSUE TITLE
Layout Grid Not showing in windows build

### ISSUE THREAD

**Issue by MeetChaudhari** [shyndman/flutter_layout_grid#87]
I just made an app for windows platform, it works fine in dev mode, with everything hot reload/restart , but when i build the app its not working, the layout grid is not showing

**Comment by shyndman** [comment]
Hey @MeetChaudhari,

Any exceptions?

**Comment by shyndman** [comment]
Closing this off for now. Feel free to reply if you'd like this reopened.
