### ISSUE TITLE
Overlap documentation?

### ISSUE THREAD

**Issue by oravecz** [shyndman/flutter_layout_grid#90]
There is mention about support for overlap in the general README, however I have been through the docs, examples, and issues and cannot find mention of how this is accomplished. Can an example be attached to the docs or examples?

FWIW, I'm trying to create a layout something like this:
![image](https://user-images.githubusercontent.com/297712/192829578-d9b9f150-4e82-4092-afa5-2d32129d66c4.png)

**Comment by shyndman** [comment]
Hm, you're right. I'll have to add something.

If you're looking to be unblocked, the rule is pretty easy: `children` are drawn in order (similarly to a [`Stack`](https://api.flutter.dev/flutter/widgets/Stack-class.html)).

In your case, orange nav would come after green header in the `children` list, and you'd use the [numeric row/column placement API](https://github.com/shyndman/flutter_layout_grid/#child-placement-by-row-and-column-indexes) to indicate the overlap.

Thanks for pointing that out. I'll put up an example shortly.

**Comment by shyndman** [comment]
I put up a [simple example](https://github.com/shyndman/flutter_layout_grid/blob/fd45e3255cf215d5b7839d72934a14ed18fa2258/example/lib/overlapping_items.dart) to demonstrate.

[![Screenshot of overlapping items example](https://user-images.githubusercontent.com/42326/192875389-c17c9ec5-80b0-4090-9baa-bd60c68d1de2.png)

Thanks for pointing that out!
