### ISSUE TITLE
This plugin doesn't work after upgrading Flutter to 3.13.1

### ISSUE THREAD

**Issue by 0Franky** [shyndman/flutter_layout_grid#96]
Hi @shyndman,
first of all thank you for your contribution!

As the title suggests, after upgrading Flutter to 3.13.1 during the compilation I retrieve errors from this plugin.

This is the log:

/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(82,55): error G79957FC8: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.     [flutter_assemble.vcxproj]
/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(83,58): error G76A9B1F6: The method 'markNeedsPlacement' isn't defined for the class 'AbstractNode?'.                 [flutter_assemble.vcxproj]
/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(84,54): error G76A9B1F6: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode?'.                    [flutter_assemble.vcxproj]
/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(132,55): error G79957FC8: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.    [flutter_assemble.vcxproj]
/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(133,58): error G76A9B1F6: The method 'markNeedsPlacement' isn't defined for the class 'AbstractNode?'.                [flutter_assemble.vcxproj]
/Pub/Cache/hosted/pub.dev/flutter_layout_grid-2.0.3/lib/src/widgets/placement.dart(134,54): error G76A9B1F6: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode?'.                   [flutter_assemble.vcxproj]

Can you help me?

Thanks in advance and have a nice day!

**Comment by shyndman** [comment]
What version are you running?

This looks like it might be the issue resolved in #91. Can you confirm?

**Comment by 0Franky** [comment]
The error was exactly that.
Even though I updated the version it didn't appear to be applying it.
I ran flutter clean and re-downloaded all packages and now it works fine.
Thank you very much!

**Comment by shyndman** [comment]
Great! Thank _you_
